INSERT INTO FilePermissions VALUES(1,'VIEW_FILE');
INSERT INTO FilePermissions VALUES(2,'VIEW_FILE');
INSERT INTO FilePermissions VALUES(4,'VIEW_FILE');
INSERT INTO FilePermissions VALUES(8,'VIEW_FILE');
INSERT INTO FilePermissions VALUES(16,'VIEW_FILE');
INSERT INTO FilePermissions VALUES(32,'VIEW_FILE');
