INSERT INTO FolderPermissions VALUES(1,'VIEW_FOLDER');
INSERT INTO FolderPermissions VALUES(2,'CREATE_FILE_WITHIN_FOLDER');
INSERT INTO FolderPermissions VALUES(4,'CEARET_FOLDER_WITHIN_FOLDER');
INSERT INTO FolderPermissions VALUES(8,'MODIFIY_FOLDER');
